# =====================
# Parent Group
# =====================
[network_devices]
cisco
fortinet
aruba

# =====================
# Cisco Groups
# =====================
[cisco]
cisco_routers
cisco_switches

[cisco:vars]
ansible_user=admin
ansible_password=secretpassword
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_become=yes
ansible_become_method=enable
ansible_become_password=enablepassword

# =====================
# Cisco Routers
# =====================
[cisco_routers]
csr01 ansible_host=192.168.122.10
csr02 ansible_host=192.168.122.11
csr03 ansible_host=192.168.122.12
csr04 ansible_host=192.168.122.13

# =====================
# Cisco Switches
# =====================
[cisco_switches]
csw01 ansible_host=192.168.122.15
csw02 ansible_host=192.168.122.16
csw03 ansible_host=192.168.122.17
csw04 ansible_host=192.168.122.18
